### ISSUE TITLE
Tags support like smartCheckbox

### ISSUE THREAD

**Issue by ftrotter** [rmariuzzo/checkboxes.js#16]
Thank you for doing a comprehensive, well tested, modern library that is compatible with bootstrap... 

It really just fits the bill and is 95% of what I need. 

The only feature that I have seen that is terribly useful is the "tagging" support that smartCheckbox has

https://github.com/jeffwa/smartCheckbox

Its clever because it enables arbitrary combinations of checkboxes to slave to one "master" checkbox by using the id of the master checkbox as a css class. 

That means that you can support really complex check-box heavy interfaces and still have really smart "you probably want this combination" type things setup...

In any case, thank you very much for the work you have already contributed.

**Comment by rmariuzzo** [comment]
Mmm... that's an interesting feature that could be added. I will think a little more on it. Can you elaborate more please?
