### ISSUE TITLE
Check all should not check invisible checkboxes

### ISSUE THREAD

**Issue by ftrotter** [rmariuzzo/checkboxes.js#17]
If I have other code that is hiding checkboxes from view, I dont want them checked when I do "check all". 

I am using tablesorter jquery plugin to filter a massive table, then I want to say "yes check all of these that I can see" and know that only the results of my filter have been checked... 

Of course, if this is not the default behavior.. then it would be nice to be able to at least configure this...

-FT

**Comment by rmariuzzo** [comment]
I agree,  I will add an option for this.

**Comment by forsbergplustwo** [comment]
+1 This would make an already awesome library even better :)

**Comment by rmariuzzo** [comment]
I will work on this.

**Comment by rmariuzzo** [comment]
Fixed and released: https://github.com/rmariuzzo/checkboxes.js/releases/tag/v1.0.7

_Sorry for the long wait..._
