### ISSUE TITLE
Range selection not working when using a 'label' tag

### ISSUE THREAD

**Issue by zverevalexei** [rmariuzzo/checkboxes.js#18]
Hi

I have a set of checkboxes on my site; each checkbox has a <i>label</i> tag assigned. When I press <i>SHIFT</i> and click on a labeled checkbox it doesn't work. I do have to click on the mere checkbox to make it work. 

Expected behavior: no matter where I click on: on the checkbox, or on the assigned 'label' element. The both should work.

Thanks.

- Alexei

**Comment by rmariuzzo** [comment]
Thanks @zverevalexei for posting this _known_ bug. We are following the discussion here: https://github.com/rmariuzzo/checkboxes.js/issues/7
