### ISSUE TITLE
jQuery throws "Uncaught RangeError: Maximum call stack size exceeded" for large range

### ISSUE THREAD

**Issue by stephenfin** [rmariuzzo/checkboxes.js#30]
I want to be able to select and unselect all checkboxes in a table by clicking the checkbox in the title row. This is how I've achieved this:

https://github.com/getpatchwork/patchwork/blob/c93e8a3ebe3a6ff9590223686d5ce56a30201250/patchwork/templates/patchwork/partials/patch-list.html#L42-L49

However, with things done this way, I note that there's a large delay between when I click that checkbox and when the selection is made. In addition, I see the following warning appearing in the console.

```
jquery-3.3.1.min.js:2 Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Function.oe [as find] (jquery-3.3.1.min.js:2)
    at w.fn.init.find (jquery-3.3.1.min.js:2)
    at Checkboxes.check (jquery.checkboxes.js:23)
    at HTMLTableElement.each (jquery.checkboxes.js:134)
    at Function.each (jquery-3.3.1.min.js:2)
    at w.fn.init.each (jquery-3.3.1.min.js:2)
    at w.fn.init.$.fn.checkboxes (jquery.checkboxes.js:123)
    at HTMLInputElement.<anonymous> ((index):386)
    at HTMLInputElement.dispatch (jquery-3.3.1.min.js:2)
```

This appears to be because `trigger('change')` is being called for every checkbox in the table.

https://github.com/rmariuzzo/checkboxes.js/blob/76c3c1746826d9b09a3e96f948c1108282fe6c43/src/jquery.checkboxes.js#L27

I rarely work with JS/jQuery so I'm not sure if there's a simple workaround for this that doesn't involve simply removing all those calls? Is this something that could be configurable or is there something I should be doing to chain these or disable them?

**Comment by stephenfin** [comment]
Wait - I sussed this almost immediately after posting it. The element I was calling `checkboxes` on includes the header checkbox. I needed to change this:

```
if(this.checked) {
    $('#patchlist').checkboxes('check');
} else {
    $('#patchlist').checkboxes('uncheck');
}
```

to

```
if(this.checked) {
    $('#patchlist > tbody').checkboxes('check');
} else {
    $('#patchlist > tbody').checkboxes('uncheck');
}
```

Sorry for the noise :smile:

**Comment by rmariuzzo** [comment]
All good @stephenfin !
