### ISSUE TITLE
Range select callback (or another way to detect when range-select checks a bunch of boxes)

### ISSUE THREAD

**Issue by dkisselev** [rmariuzzo/checkboxes.js#8]
I really love the functionality of this plugin, but I'm running into some trouble with using range select on dynamically generated checkboxes.

I have a page that's creating a bunch of checkboxes based on the results of a jQuery AJAX API call. So the only way to detect when they change is to bind to the change property of the div that surrounds all the boxes.

Unfortunately, when someone shift-selects, the change event is only fired once, and although on-screen, all the boxes in the range get checked, there isn't any way (that I can tell) to programatically detect which boxes are now selected and which aren't without iterating over each item and manually checking its checked property.

Unfortunately, the application I have now has 1500 checkboxes in a single long list, so iterating over all of them is too slow. (especially when I know that most of the time, no more than 10-20 items would have changed)

The only way I can think of solving this would be to have the library call a callback function that I configure whenever it checks/unchecks a box, but I'm open to any other ideas.

**Comment by rmariuzzo** [comment]
Rethinking on this, I'm wondering if it would be good to add a custom event, such as: `change.checkboxes` where it returns an event object with a array of changed checkboxes.

**Comment by rmariuzzo** [comment]
Fixed: https://github.com/rmariuzzo/checkboxes.js/releases/tag/v1.2.0
